import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Application } from '../libs/components/application/application';
import { store } from '../libs/store/store';
import '../styles/globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Application store={store}>{children}</Application>
            </body>
        </html>
    );
}
