import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { PropsWithChildren } from 'react';
import { Application } from '../libs/components/application/application';
import { NavbarProps } from '../libs/components/navbar/navbar.component';
import '../styles/globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<PropsWithChildren>) {
    const navbarItems: NavbarProps['navbars'] = [
        {
            title: 'Index page',
            name: 'Index',
            path: '/',
        },
        {
            title: 'About us page',
            name: 'About',
            path: '/about',
        },
        {
            title: 'Contact us page',
            name: 'Contact us',
            path: '/contact',
        },
        {
            title: 'Team members',
            name: 'Team',
            path: '/team',
        },
        {
            title: 'Terms and conditions page',
            name: 'Terms and conditions',
            path: '/terms-and-conditions',
        },
        {
            title: 'Resume page',
            name: 'Resume',
            path: '/resume',
        },
    ];

    return (
        <html lang="en">
            <body className={inter.className}>
                <Application navbarItems={navbarItems}>
                    {children}
                </Application>
            </body>
        </html>
    );
}
