import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { PropsWithChildren } from 'react';
import {
    Navbar,
    NavbarProps,
} from '../libs/components/navbar/navbar.component';
import '../styles/globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<PropsWithChildren>) {
    const navbars: NavbarProps['navbars'] = [
        {
            title: 'About us page',
            name: 'About',
            path: '/about',
        },
        {
            title: 'Index page',
            name: 'Index',
            path: '/',
        },
    ];

    return (
        <html lang="en">
            <body className={inter.className}>
                <Navbar navbars={navbars} />
                {children}
            </body>
        </html>
    );
}
